/*
 * This source file was generated by the Gradle 'init' task
 */



package edu.info0502.tp1;

import edu.info0502.tp1.Media;
import edu.info0502.tp1.Film;
import edu.info0502.tp1.Mediatheque;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Mediatheque maMediatheque = new Mediatheque();
        maMediatheque.setNomProprietaire("Alice Martin");

        Film film1 = new Film("Le Seigneur des Anneaux : La Communauté de l'Anneau", 
                              new StringBuffer("F001"), 9, "Peter Jackson", 2001);
        Film film2 = new Film("Inception", 
                              new StringBuffer("F002"), 10, "Christopher Nolan", 2010);

        maMediatheque.add(film1);
        maMediatheque.add(film2);

        Media livre1 = new Media("Harry Potter à l'école des sorciers", 
                                 new StringBuffer("L001"), 8);

        maMediatheque.add(livre1);

        System.out.println("Médiathèque d'Alice Martin :");
        System.out.println(maMediatheque);

        Mediatheque copieMediatheque = new Mediatheque(maMediatheque);
        copieMediatheque.setNomProprietaire("Bob Dupont");

        Film film3 = new Film("Interstellar", 
                              new StringBuffer("F003"), 10, "Christopher Nolan", 2014);
        copieMediatheque.add(film3);

        System.out.println("Médiathèque d'Alice après copie :");
        System.out.println(maMediatheque);
        System.out.println("Copie de la médiathèque, appartenant à Bob Dupont :");
        System.out.println(copieMediatheque);
    }
}
